-- ═══ GmbPro Schema ═══

-- Clients (linked to Supabase auth.users)
CREATE TABLE clients (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  business_name TEXT NOT NULL,
  city TEXT NOT NULL,
  phone TEXT,
  plan TEXT NOT NULL DEFAULT 'starter' CHECK (plan IN ('starter', 'pro', 'premium')),
  stripe_customer_id TEXT,
  stripe_subscription_id TEXT,
  subscription_status TEXT DEFAULT 'inactive' CHECK (subscription_status IN ('active', 'inactive', 'cancelled', 'past_due')),
  gmb_score INTEGER,
  last_audit_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Audits history
CREATE TABLE audits (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID REFERENCES clients(id) ON DELETE CASCADE,
  place_id TEXT,
  business_name TEXT NOT NULL,
  city TEXT NOT NULL,
  global_score INTEGER NOT NULL,
  passed_count INTEGER NOT NULL,
  failed_count INTEGER NOT NULL,
  total_criteria INTEGER NOT NULL DEFAULT 27,
  rating NUMERIC(2,1),
  review_count INTEGER,
  photo_count INTEGER,
  categories JSONB NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Scan requests (anonymous scans from landing page)
CREATE TABLE scans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  place_id TEXT,
  business_name TEXT NOT NULL,
  city TEXT NOT NULL,
  global_score INTEGER NOT NULL,
  email TEXT,
  ip TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- GMB Posts (generated by AI, published via API)
CREATE TABLE gmb_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID REFERENCES clients(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'scheduled', 'published', 'failed')),
  scheduled_at TIMESTAMPTZ,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Review responses (generated by AI)
CREATE TABLE review_responses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID REFERENCES clients(id) ON DELETE CASCADE,
  review_author TEXT,
  review_rating INTEGER,
  review_text TEXT,
  response_text TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'approved', 'published')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Keyword positions tracking
CREATE TABLE keyword_positions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID REFERENCES clients(id) ON DELETE CASCADE,
  keyword TEXT NOT NULL,
  position INTEGER,
  previous_position INTEGER,
  search_volume INTEGER,
  checked_at TIMESTAMPTZ DEFAULT NOW()
);

-- ═══ RLS Policies ═══

ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE audits ENABLE ROW LEVEL SECURITY;
ALTER TABLE scans ENABLE ROW LEVEL SECURITY;
ALTER TABLE gmb_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE review_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE keyword_positions ENABLE ROW LEVEL SECURITY;

-- Clients: users can only see/edit their own data
CREATE POLICY "clients_own" ON clients FOR ALL USING (auth.uid() = id);

-- Audits: users see their own audits
CREATE POLICY "audits_own" ON audits FOR ALL USING (auth.uid() = client_id);

-- Scans: insert only (anonymous), no read
CREATE POLICY "scans_insert" ON scans FOR INSERT WITH CHECK (true);

-- GMB Posts: users see their own
CREATE POLICY "posts_own" ON gmb_posts FOR ALL USING (auth.uid() = client_id);

-- Review responses: users see their own
CREATE POLICY "responses_own" ON review_responses FOR ALL USING (auth.uid() = client_id);

-- Keyword positions: users see their own
CREATE POLICY "positions_own" ON keyword_positions FOR ALL USING (auth.uid() = client_id);

-- ═══ Indexes ═══
CREATE INDEX idx_audits_client ON audits(client_id);
CREATE INDEX idx_scans_email ON scans(email);
CREATE INDEX idx_posts_client ON gmb_posts(client_id);
CREATE INDEX idx_positions_client ON keyword_positions(client_id);
CREATE INDEX idx_scans_created ON scans(created_at DESC);

-- ═══ Prospects (businesses scanned from cities/sectors) ═══

CREATE TABLE IF NOT EXISTS prospects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  place_id TEXT UNIQUE,
  business_name TEXT NOT NULL,
  city TEXT NOT NULL,
  sector TEXT,
  address TEXT,
  phone TEXT,
  website TEXT,
  email TEXT,
  global_score INTEGER,
  passed_count INTEGER,
  failed_count INTEGER,
  rating NUMERIC(2,1),
  review_count INTEGER,
  photo_count INTEGER,
  status TEXT DEFAULT 'new' CHECK (status IN ('new', 'emailed', 'converted', 'rejected', 'invalid')),
  source TEXT DEFAULT 'google_places',
  last_contacted_at TIMESTAMPTZ,
  email_count INTEGER DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_prospects_score ON prospects(global_score);
CREATE INDEX IF NOT EXISTS idx_prospects_status ON prospects(status);
CREATE INDEX IF NOT EXISTS idx_prospects_city ON prospects(city);

-- Prospection campaigns
CREATE TABLE IF NOT EXISTS prospection_campaigns (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  sector TEXT NOT NULL,
  max_results INTEGER DEFAULT 20,
  results_count INTEGER DEFAULT 0,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'completed', 'failed')),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE prospects ENABLE ROW LEVEL SECURITY;
ALTER TABLE prospection_campaigns ENABLE ROW LEVEL SECURITY;

-- Policies permissives (l'acces est gere cote API via mot de passe admin)
CREATE POLICY "prospects_insert_all" ON prospects FOR INSERT WITH CHECK (true);
CREATE POLICY "prospects_select_all" ON prospects FOR SELECT USING (true);
CREATE POLICY "prospects_update_all" ON prospects FOR UPDATE USING (true);
CREATE POLICY "campaigns_all" ON prospection_campaigns FOR ALL USING (true) WITH CHECK (true);

-- Apres avoir execute ce SQL dans Supabase, verifie que les nouvelles tables
-- (prospects, prospection_campaigns) sont bien creees.

-- ═══ Migration: tracking conversion email + region ═══
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS region TEXT;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS email_sent_at TIMESTAMPTZ;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS email_opened_at TIMESTAMPTZ;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS email_clicked_at TIMESTAMPTZ;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS email_bounced BOOLEAN DEFAULT false;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS resend_email_id TEXT;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS signup_at TIMESTAMPTZ;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS converted_at TIMESTAMPTZ;

ALTER TABLE prospection_campaigns ADD COLUMN IF NOT EXISTS region TEXT;

CREATE INDEX IF NOT EXISTS idx_prospects_region ON prospects(region);
CREATE INDEX IF NOT EXISTS idx_prospects_resend_email_id ON prospects(resend_email_id);

-- ═══ Migration: Google Business Profile OAuth tokens (per client) ═══
ALTER TABLE clients ADD COLUMN IF NOT EXISTS google_access_token TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS google_refresh_token TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS google_token_expires_at TIMESTAMPTZ;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS google_email TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS gmb_account_id TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS gmb_account_name TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS gmb_location_id TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS gmb_location_name TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS gmb_connected_at TIMESTAMPTZ;

-- ═══ Migration: Settings extra + Manager invite + Optimization tasks ═══

-- Client settings extra fields
ALTER TABLE clients ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS sector TEXT;

-- Manager invitation tracking
ALTER TABLE clients ADD COLUMN IF NOT EXISTS manager_invite_status TEXT DEFAULT 'pending' CHECK (manager_invite_status IN ('pending', 'sent', 'accepted', 'refused'));
ALTER TABLE clients ADD COLUMN IF NOT EXISTS manager_invite_at TIMESTAMPTZ;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS manager_accepted_at TIMESTAMPTZ;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS manager_email_used TEXT;

-- Optimization tasks (program)
CREATE TABLE IF NOT EXISTS optimization_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID REFERENCES clients(id) ON DELETE CASCADE,
  category TEXT NOT NULL,
  task_type TEXT NOT NULL,
  title TEXT NOT NULL,
  why TEXT,
  instructions TEXT,
  content_to_copy TEXT,
  priority INTEGER DEFAULT 1,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'done', 'skipped')),
  done_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_opt_tasks_client ON optimization_tasks(client_id);
CREATE INDEX IF NOT EXISTS idx_opt_tasks_status ON optimization_tasks(status);

ALTER TABLE optimization_tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tasks_own" ON optimization_tasks FOR ALL USING (auth.uid() = client_id);

